name: Generate Datas
on:
  schedule:
    # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      
      - name: Generate contribution snake
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: haffarsadok
          svg_out_path: github-contribution-grid-snake.svg
      
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
